[project]
name = "mycologue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy>=4.5.3",
    "click>=8.3.0",
    "ipykernel>=6.30.1",
    "ipython>=9.5.0",
    "tqdm>=4.67.1",
]
